
clone_depth: 5

image:
  - Visual Studio 2019
  - Visual Studio 2017

platform:
  - x64
  - Win32

configuration:
  - RelWithDebInfo
  - Debug

clone_folder: c:\project

init:
  - msbuild /version
  - cmake --version

before_build:
  - git submodule update --init --recursive
  - mkdir build && cd build
  - if "%APPVEYOR_BUILD_WORKER_IMAGE%"=="Visual Studio 2017" cmake -G"Visual Studio 15 2017" -A "%PLATFORM%" ..
  - if "%APPVEYOR_BUILD_WORKER_IMAGE%"=="Visual Studio 2019" cmake -G"Visual Studio 16 2019" -A "%PLATFORM%" ..

build:
  project: c:\project\build\degrid.sln

test_script:
  - c:\project\build\result\%CONFIGURATION%\cage-asset-database.exe

