
clone_depth: 5

image: Visual Studio 2017

platform:
  - Win32
  - x64

configuration:
  - Debug
  - RelWithDebInfo

clone_folder: c:\project

init:
  - cmake --version
  - msbuild /version

install:
  - git submodule update --init --recursive

before_build:
  - mkdir build
  - cd build
  - if "%PLATFORM%"=="Win32" cmake -G"Visual Studio 15 2017" ..
  - if "%PLATFORM%"=="x64" cmake -G"Visual Studio 15 2017 Win64" ..

build:
  project: c:\project\build\grid.sln

test_script:
  - c:\project\build\result\%CONFIGURATION%\cage-asset-database.exe

